//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherApp.Resources.AppTranslations", typeof(AppTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily forecast.
        /// </summary>
        internal static string DailyForecast {
            get {
                return ResourceManager.GetString("DailyForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly forecast.
        /// </summary>
        internal static string HourlyForecast {
            get {
                return ResourceManager.GetString("HourlyForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MissingLocalizationClose {
            get {
                return ResourceManager.GetString("MissingLocalizationClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing localization permissions.
        /// </summary>
        internal static string MissingLocalizationPermissions {
            get {
                return ResourceManager.GetString("MissingLocalizationPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access to localization, turn access on in settings.
        /// </summary>
        internal static string MissingLocalizationText {
            get {
                return ResourceManager.GetString("MissingLocalizationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MissingLocalizationTitle {
            get {
                return ResourceManager.GetString("MissingLocalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string NoInternetClose {
            get {
                return ResourceManager.GetString("NoInternetClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection.
        /// </summary>
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet access.
        /// </summary>
        internal static string NoInternetText {
            get {
                return ResourceManager.GetString("NoInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string NoInternetTitle {
            get {
                return ResourceManager.GetString("NoInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost.
        /// </summary>
        internal static string NotificationFrost {
            get {
                return ResourceManager.GetString("NotificationFrost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        internal static string NotificationRain {
            get {
                return ResourceManager.GetString("NotificationRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification
        ///hour:.
        /// </summary>
        internal static string NotificationSendTime {
            get {
                return ResourceManager.GetString("NotificationSendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        internal static string NotificationSnow {
            get {
                return ResourceManager.GetString("NotificationSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm.
        /// </summary>
        internal static string NotificationStorm {
            get {
                return ResourceManager.GetString("NotificationStorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from {0}.
        /// </summary>
        internal static string OldDataFrom {
            get {
                return ResourceManager.GetString("OldDataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string SettingsSetTemperatureClose {
            get {
                return ResourceManager.GetString("SettingsSetTemperatureClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string SettingsSetTemperatureTitle {
            get {
                return ResourceManager.GetString("SettingsSetTemperatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string SettingsSetWindSpeedClose {
            get {
                return ResourceManager.GetString("SettingsSetWindSpeedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        internal static string SettingsSetWindSpeedTitle {
            get {
                return ResourceManager.GetString("SettingsSetWindSpeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string SettingsTemperature {
            get {
                return ResourceManager.GetString("SettingsTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        internal static string SettingsWind {
            get {
                return ResourceManager.GetString("SettingsWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise {0}.
        /// </summary>
        internal static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset {0}.
        /// </summary>
        internal static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string TabNotifications {
            get {
                return ResourceManager.GetString("TabNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        internal static string TabWeather {
            get {
                return ResourceManager.GetString("TabWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string WidgetLoading {
            get {
                return ResourceManager.GetString("WidgetLoading", resourceCulture);
            }
        }
    }
}
